# Generated by Django 5.0 on 2024-02-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('PH', models.FloatField()),
                ('RainFall', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
