# Generated by Django 4.2.7 on 2024-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nic',
            field=models.CharField(default='null', max_length=100, verbose_name='NIC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default='null', max_length=100, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default='null', max_length=100, verbose_name='Telephone Number'),
            preserve_default=False,
        ),
    ]
