# Generated by Django 4.2.7 on 2024-02-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nic_user_province_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
    ]
